### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by amirouche** [awesome-data-distribution/datae#2]
- [ ] SPARQL support https://www.w3.org/TR/rdf-sparql-query/ https://www.w3.org/TR/sparql11-overview/
  - [x] fix the bug when the database is empty
  - [x] Create a parser combinator library that works with `streams.scm`
  - [ ] Add filter support
  - [x] Implement query engine based on the semantic of SPARQL https://www.w3.org/TR/rdf-sparql-query/ https://www.w3.org/TR/sparql11-overview/
  - [x] Rename some `bind` procedure to `join`
  - [x] There is some shenanigan in the query engine regarding patterns, I think it recomputes patterns binding several times. Also patterns must be resolved to uids ASAP.
  - [x] Implement `ORDER BY`
  - [x] Implement `GROUP BY`
  - [ ] Parse SPARQL using parser combinators
  - [ ] Run SPARQL using neon query engine
  - [ ] ~Add support for OPTIONAL expressed as multiple clauses~ multiple clauses is not equivalent to OPTIONAL
- [ ] Check TODO in the code
- [x] Maybe merge guid, puid, suid, ouid into a single table and make all of them scheme values
- [x] create a safe read
- [x] Implement del procedure
- [ ] Make history of a branch an attribute of <neon> with fash and atomic read / write
- [ ] import/export n-quads https://www.w3.org/TR/n-quads/
- [ ] Turtle parser https://www.w3.org/TR/turtle/
- [ ] Create command line interface
- [ ] Create database server
- [ ] Pass w3c tests http://w3c.github.io/rdf-tests/
- [ ] Add the ability to import/export to/from sexpr
- [ ] Change the way sha256 is computed
- [ ] Implement push / pull between two local repositories
- [ ] Implement push / pull between two remote servers
- [ ] Create algorithm to help with merge
- [ ] Add message in transactions
- [ ] Add the ability to import/export to/from nquads
- [ ] Add the ability to squash transactions
- [ ] Add tests
- [ ] Make backend storage pluggable
- [ ] Add postgresql backend with guile-squee https://notabug.org/cwebber/guile-squee/
- [ ] Add signed byte 'b' in wiredtiger and replace tombstone with -1 1.
- [ ] Add literal support https://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal maybe do not do it since it is debated that is not useful.

Questions:

- performance of msgpack vs scheme read/write? but scheme allows to bignums
- how to handle graphs in the history? right now, graphs can not be deleted

**Comment by amirouche** [comment]
I will create another TODO to track new code implementation
